server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/summer?useSSL=true&erverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  type-aliases-package: team.redrock.mybatisdemo1.entity




